
-- Table: TEILNEHMER
CREATE TABLE IF NOT EXISTS TEILNEHMER (
    id_num INTEGER PRIMARY KEY AUTOINCREMENT,
    vorname TEXT NOT NULL,
    nachname TEXT NOT NULL,
    pw TEXT NOT NULL
);

-- Table: SEMINAR
CREATE TABLE IF NOT EXISTS SEMINAR (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    street TEXT NOT NULL,
    date TEXT NOT NULL,   -- Format: YYYY-MM-DD
    time TEXT NOT NULL    -- Format: HH:MM
);

-- Table: BUCHUNG (booking table)
CREATE TABLE IF NOT EXISTS BUCHUNG (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    teilnehmer_id INTEGER NOT NULL,
    seminar_id INTEGER NOT NULL,
    FOREIGN KEY (teilnehmer_id) REFERENCES TEILNEHMER(id_num) ON DELETE CASCADE,
    FOREIGN KEY (seminar_id) REFERENCES SEMINAR(id) ON DELETE CASCADE
);